### ISSUE TITLE
Access Blocked

### ISSUE THREAD

**Issue by deltaxsingh** [Juby210/SwiftBackupPrem#1]
Followed the step by step instructions but still ended up with:

"You can't sign in because [project name] sent an invalid request" 

```
Error 400: invalid_request
Custom URI scheme is not enabled for your Android client. 
```

Not sure how to fix this. Followed the tutorial exactly.

**Comment by Juby210** [comment]
Hello! Apparently Google disabled Custom URI schemes by default for new projects a month ago.
Go to https://console.cloud.google.com/apis/credentials then select `Android client` and edit it
![image](https://github.com/Juby210/SwiftBackupPrem/assets/31005896/0c159acf-788a-448c-a3aa-eb71ede18717)
