### ISSUE TITLE
About the new version

### ISSUE THREAD

**Issue by Oopas** [Juby210/SwiftBackupPrem#2]
I successfully backed up the data to the FTP server using this software. However, recently both 4.2.3 and 4.2.5 have indicated that they are no longer supported and are flashing, while in versions above 5.0.0, this module has indicated that it cannot be fully hooked.

Is there any way to prevent the logout of 4.2.3 and 4.2.5 while connected to the internet?

Thanks😉

**Comment by Juby210** [comment]
Hello, I updated the module to support v5.0.4+ versions, it should work now https://github.com/Juby210/SwiftBackupPrem/releases/tag/v2.0.4
