### ISSUE TITLE
Android 15

### ISSUE THREAD

**Issue by compicat** [Juby210/SwiftBackupPrem#6]
Thanks for this amazing module. Could you please make it compatible with a15 too? It works with los 21, but not with los 22. Module is not opening both with kernelsu or magisk. Setup is lsposed mod and zygisk next.

**Comment by Juby210** [comment]
Not related to the module, your lsposed is broken. The only lsposed version that works on Android 15 is https://github.com/JingMatrix/LSPosed

**Comment by compicat** [comment]
@Juby210 thanks for fast and kind reply. I apologise for late reply. I tried with that lsposed too, your module is activated in lsposed but unfortunately when i try to open it, it returns to desktop and says "enable the module in lsposed" even though it is already enabled. Thanks in advance.

**Comment by compicat** [comment]
@Juby210  So sorry for trouble. Returning back to zygisk next from rezygisk and using universal auth module fixed the thing. Thanks for your all help again. Wish you best.
